version: '3'
services:
  database:
    container_name: dmp_postgres
    image: postgres
    env_file:
      - database.env
    volumes:
      - /Users/chenhao/Documents/docker-postgresql/data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"  
